#
# Module manifest for module 'PowerShell.Map'
#
# Generated by: Yoshifumi Tsuda
#
# Generated on: 2025/10/17
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PowerShell.Map.dll'

# Version number of this module.
ModuleVersion = '1.0.1'

# Supported PSEditions
CompatiblePSEditions = @('Core')

# ID used to uniquely identify this module
GUID = 'b8e7c4d1-3f2a-4a9b-8c5d-1e2f3a4b5c6d'

# Author of this module
Author = 'Yoshifumi Tsuda'

# Company or vendor of this module
CompanyName = 'Yoshifumi Tsuda'

# Copyright statement for this module
Copyright = '(c) Yoshifumi Tsuda. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Interactive 2D/3D map visualization for PowerShell using MapLibre GL JS and OpenStreetMap. Although usable standalone, this module is primarily designed for Claude Desktop integration via the PowerShell.MCP module, enabling AI-powered map visualization.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.2'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @('PowerShell.Map.Format.ps1xml')

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('PowerShell.Map.psm1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
'Show-OpenStreetMap',
'Show-OpenStreetMapRoute',
'Start-OpenStreetMapTour'
)

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Map','Visualization','GIS','Leaflet','OpenStreetMap','Route','Geocoding','Interactive'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/yotsuda/PowerShell.Map/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/yotsuda/PowerShell.Map'

        # A URL to an icon representing this module.
        # IconUri = ''

        Platforms = @('Windows')

        # ReleaseNotes of this module
        ReleaseNotes = 'PowerShell.Map v1.0.1 - 3D Map Support & Enhanced Descriptions

=== What''s New in v1.0.1 ===
• 🎮 3D Map Visualization - Interactive 3D terrain and building views
• 📝 Location Descriptions - Display detailed information for each marker

=== Key Features ===
• 🗺️ Interactive 2D/3D OpenStreetMap Display
• 🛣️ Route Visualization with Turn-by-Turn Directions
• 🎬 Animated Tours for Multiple Locations
• 🌍 Geocoding & Reverse Geocoding
• 📍 Multiple Markers with Custom Colors and Descriptions
• ⚡ Smooth Animations with Duration Control
• 🎯 CSV Pipeline Support

=== Quick Start ===
1. Import-Module PowerShell.Map
2. Show-OpenStreetMap Tokyo
3. Show-OpenStreetMapRoute -From Tokyo -To Osaka
4. Start-OpenStreetMapTour Tokyo, Kyoto, Osaka

=== Examples ===
# Display a location
Show-OpenStreetMap "Tokyo Tower"

# Display multiple locations
Show-OpenStreetMap -Location Tokyo, Osaka, Kyoto

# With coordinates and zoom
Show-OpenStreetMap -Location "35.6586,139.7454" -Zoom 15

# With descriptions and colors
$locations = @(
    @{ Location = "Tokyo"; Description = "Capital of Japan"; Color = "red" }
    @{ Location = "Osaka"; Description = "Second largest city"; Color = "blue" }
)
Show-OpenStreetMap -Locations $locations

# 3D terrain visualization
Show-OpenStreetMap "35.3606,138.7274" -Enable3D -Zoom 11 -Pitch 70

# Show route between two locations
Show-OpenStreetMapRoute -From Tokyo -To Osaka -Color "#ff0000"

# Create animated tour
Start-OpenStreetMapTour Paris, London, Berlin -Duration 2.5 -PauseTime 2

# CSV pipeline
Import-Csv locations.csv | Show-OpenStreetMap

=== Requirements ===
Windows 10/11, PowerShell 7.2+, Internet connection (for OpenStreetMap tiles)

=== Claude Desktop Integration ===
This module integrates with Claude Desktop via PowerShell.MCP:
• PowerShell Gallery: https://www.powershellgallery.com/packages/PowerShell.MCP
• GitHub: https://github.com/yotsuda/PowerShell.MCP

=== Documentation ===
Full documentation: https://github.com/yotsuda/PowerShell.Map#readme
'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/yotsuda/PowerShell.Map#readme'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
